name: Deploy GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v3
        with:
          enablement: true

      - name: Upload static site
        uses: actions/upload-pages-artifact@v3
        with:
          path: demos

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
