name: Deploy HTML Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 关键点1：必须使用 public 目录
      - name: Prepare files
        run: |
          mkdir -p ./public
          cp -r demos/mcp/* ./public/
          echo "Files to deploy:" && ls -R ./public

      # 关键点2：显式指定同名 artifact
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'public'
          name: 'pages_artifact'  # 自定义名称

      # 关键点3：部署时使用相同名称
      - name: Deploy
        uses: actions/deploy-pages@v3
        with:
          artifact_name: 'pages_artifact'  # 必须与上传名称一致
