name: Deploy Private Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 构建符合你要求的目录结构
      - name: Prepare files
        run: |
          mkdir -p ./public/demos/mcp
          cp -r demos/mcp/* ./public/demos/mcp/
          echo "jch.ai" > ./public/CNAME
          tree ./public

      # 官方推荐部署方式（兼容私有仓库）
      - name: Deploy
        uses: actions/deploy-pages@v3
