name: Deploy HTML Pages
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/deploy-pages@v3
        with:
          target_branch: gh-pages
          publish_dir: ./demos/mcp
