name: Deploy HTML Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare artifact
        run: |
          mkdir -p public
          cp -r demos/mcp/* public/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'public'
          name: 'pages-artifact'

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v3
        with:
          artifact_name: 'pages-artifact'
